### ISSUE TITLE
Confusing flow of files - Diagram may help(included)

### ISSUE THREAD

**Issue by mineshmshah** [foundersandcoders/express-handlebars-workshop#15]
The flow for this exercise in the way that how express calls handlebars is confusing. 
I created a flow diagram(below) to explain the flow a bit better which people found helpful.  Maybe wise to include it so students can visualise things better.

![express handlebars flow chart](https://user-images.githubusercontent.com/19519073/33936381-3dd1f3e6-dff7-11e7-8edb-1ba0433e635a.png)

**Comment by Johanna-hub** [comment]
Thanks @mineshmshah, this was super useful!

**Comment by eliascodes** [comment]
@mineshmshah do you have the source file that generated this diagram, so we can make edits?

**Comment by jamiecoe** [comment]
@eliascodes Minesh has given me the source file, so we can make edits 🎉 Was there anything that needed to be changed? Just double checked and I think it's still up-to-date with our workshop instruction edits.

**Comment by eliascodes** [comment]
@jamiecoe if the diagram looks sensible to you, I'm happy for you to leave it as is. Though I'd like the source file for the diagram to be committed, perhaps you can rename the `images-readme` directory to `assets` or `docs` or something and stick it in there?

**Comment by thejoefriel** [comment]
Hi @mineshmshah - I'm on fac14 and currently doing curriculum review. It appears this image was added to the readme so are you happy to close this issue?
