### ISSUE TITLE
remove explanation of MVC model

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/express-handlebars-workshop#2]
Ideally, each portion of the curriculum should be composable. The MVC model isn't specific to express week. In future, we might choose to include this in a node week, or elsewhere in the course. (Let's move it into it's own repo - https://github.com/foundersandcoders/master-reference/issues/575)

+ [ ] Remove the MVC section from this readme

**Comment by thejoefriel** [comment]
Hi @jsms90 - on fac14 and doing the curriculum review. Am I right that this explanation has been removed from the readme? If so, are you happy to close this issue?

**Comment by BartBucknill** [comment]
@thejoefriel Looks like it has indeed been removed - I think it's fine to go ahead and close the issue.
