### ISSUE TITLE
Does Step 13 refer to the correct file?

### ISSUE THREAD

**Issue by rachaelcodes** [foundersandcoders/express-handlebars-workshop#8]
Step 13 says:  Use render function in `src/controllers/fruits.js` to render individual fruit. Extract name from the params.

Should this be `src/controllers/fruit.js` ? We'd added a render to fruits.js in an earlier step - I'm doing this workshop late, so it might just be my confusion though.

**Comment by rachaelcodes** [comment]
also, is step 14 for creating the `fruit.hbs` file rather than the `fruits.hbs` one?

**Comment by PiotrBerebecki** [comment]
Thanks Rachel. This will be fixed today.

**Comment by astroash** [comment]
@BartBucknill @mineshmshah do you know if this issue is still relevant after the rewrite?

**Comment by BartBucknill** [comment]
@astroash no, i'll close it
